name: open-webui

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:${OPEN_WEBUI_TAG:-main}
    container_name: open-webui

    restart: unless-stopped

    ports:
      - "127.0.0.1:3000:8080"

    volumes:
      - open-webui-data:/app/backend/data

    environment:
      WEBUI_SECRET_KEY_FILE: /app/backend/data/.webui_secret_key
      RAG_EMBEDDING_CONTENT_PREFIX: "search_document: "
      RAG_EMBEDDING_QUERY_PREFIX: "search_query: "

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - local-ai-network

volumes:
  open-webui-data:
    name: open-webui-data

networks:
  local-ai-network:
    external: true