name: searxng

services:
  searxng:
    build:
      context: .
      pull: true

    image: local/searxng:latest
    container_name: searxng

    restart: unless-stopped

    volumes:
      - searxng-cache:/var/cache/searxng

    networks:
      - local-ai-network

    ports:
      - "127.0.0.1:8888:8080"

volumes:
  searxng-cache:
    name: searxng-cache

networks:
  local-ai-network:
    external: true